### ISSUE TITLE
Feature request: Support refreshing Auth Cookies from inside a server action

### ISSUE THREAD

**Issue by abusada** [awinogrodzki/next-firebase-auth-edge#132] opened 2023-12-11 12:26 UTC
Use case: I'm handling user sign up form submission inside a server action, and since the user's claims get updated, I would need to refresh the auth cookies.

**Comment by awinogrodzki** [comment] 2023-12-19 00:30
Hey @abusada!

Thanks for reporting. 

It looks like a duplicate of https://github.com/awinogrodzki/next-firebase-auth-edge/issues/124#issuecomment-1803567433

At this moment it's impossible to manipulate response headers from Server Actions (see linked comment)

A workaround would be to call `/api/login` from client just after user sign up. 

Let me know if that helps!

**Comment by steve-marmalade** [comment] 2024-01-04 18:19
@awinogrodzki not sure if this was added recently, but Server Actions do support modifying cookies: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options

@abusada my current workaround is to run the middleware version of the `refreshAuthCookies` function, then parse the `set-cookie` header on the response and manually call `cookies().set()`. Seems to be working well for me, but definitely would be great to have a more official solution!

**Comment by awinogrodzki** [comment] 2024-01-04 18:34
Hey @steve-marmalade! Thanks for a heads up! That's wonderful news. I wasn't aware of `cookies().set(...)` method. I might have missed it or it was introduced recently. Either way, I will implement support to refresh auth cookies from inside server action.

At the moment I am working on `1.x` release with improved API's, docs and magic link support. I will work on improved Server Actions support just after I release `1.0`. 

Cheers 🎉

**Comment by awinogrodzki** [comment] 2024-02-13 15:14
Hey @abusada @steve-marmalade !

Since `next-firebase-auth-edge@1.2.0` you can now refresh auth cookies from inside Server Actions using `refreshServerCookies` function imported from `next-firebase-auth-edge/lib/next/cookies`

See https://next-firebase-auth-edge-docs.vercel.app/docs/usage/refresh-auth-cookies#refresh-auth-cookies-in-server-actions

Let me know how it works!
Cheers :tada:

**Closed by awinogrodzki** 2024-02-13 15:14 UTC
Labels: enhancement
