### ISSUE TITLE
no-matching-kid-error

### ISSUE THREAD

**Issue by Mencraft** [awinogrodzki/next-firebase-auth-edge#90] opened 2023-08-27 04:57 UTC
hello getting the error below when the user is logged in for more than a day 
 [Error: Internal error: no-matching-kid-error] {
  code: 'INTERNAL_ERROR'
}

env
    "next-firebase-auth-edge": "^0.8.3",
    "next": "^13.4.12",
    "firebase": "^9.18.0",

**Comment by awinogrodzki** [comment] 2023-08-27 12:38
Hey @Mencraft! Thanks for reporting.

Are you using Firebase Emulator? Is the error happening on local or remote server?

**Comment by dukeofsoftware** [comment] 2023-08-27 15:31
Hi! I got the same issue on local. It disappears when you logout and log in again.

**Comment by timotiusnc** [comment] 2023-08-28 11:42
I experienced the same `no-matching-kid-error`.

The situation when I experienced it:
1. Happened in both my local and production website.
2. It happened on a Monday, where I have not visited the website since last Saturday.
3. Clearing the cookies solved the problem (both local and production).

Point 2 seems similar with @Mencraft (`...when the user is logged in for more than a day`).

So it seems the problem only happens after a certain period of time of inactivity (I haven't found the definitive reproducible steps, yet).

My versions:
```
"next-firebase-auth-edge": "^0.8.0",
"next": "13.4.12",
"firebase": "^10.1.0",
```

**Comment by Mencraft** [comment] 2023-08-28 14:54
> Hey @Mencraft! Thanks for reporting.
> 
> Are you using Firebase Emulator? Is the error happening on local or remote server?

i am not using firebase emulator. happening both on local and production

**Comment by awinogrodzki** [comment] 2023-08-29 10:01
@timotiusnc @Mencraft  thanks for the details! I will work on this today

**Comment by awinogrodzki** [comment] 2023-08-29 20:32
@Mencraft @timotiusnc @dukeofsoftware 

The issue is fixed in `next-firebase-auth-edge@0.8.4`

If you are interested in the reason behind the issue:

Each id token generated by Firebase is equipped with `kid` value in header. 
This value corresponds with one of the keys of [Google public x509 certificates](https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com)

`next-firebase-auth-edge` does refetch those certificates every ~6 hours

Up till now, if token `kid` was not present in google certificates list, `NO_MATCHING_KID` error was thrown.

I looked up how this scenario is being handled by official `firebase-admin` library. `firebase-admin` expects `kid` not to be matching. In such case, token is validated against all certificates returned by Google. (https://github.com/firebase/firebase-admin-node/blob/bd8a11106c4af22d2fd46c84158d1a80e7d4828a/src/utils/jwt.ts#L213)

I've also added number of unit tests that handle this exact use case:
https://github.com/awinogrodzki/next-firebase-auth-edge/pull/91

Please let me know if that works!

**Comment by timotiusnc** [comment] 2023-08-30 03:48
@awinogrodzki thank you !!

One question:
```
In case there is no "kid" claim matching available certficates, you should see following error:
...
What you should do, is just redirect to /login in case of INVALID_ARGUMENT error.
```

When that error happens, do you think we should *remove the cookies* before redirecting to login? Because when I got that error before, it created `too many redirection` error. Hence, I think the app will get into the same `too many redirection` error when `AuthError(AuthErrorCode.INVALID_ARGUMENT...` is thrown.

Or is there anything I missed?

**Comment by awinogrodzki** [comment] 2023-08-30 09:17
Hey @timotiusnc,

Here's the `redirectToLogin` code from latest starter example:

```typescript
const PUBLIC_PATHS = ["/register", "/login", "/reset-password"];
```

```typescript
function redirectToLogin(request: NextRequest) {
  if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
    return NextResponse.next();
  }

  const url = request.nextUrl.clone();
  url.pathname = "/login";
  url.search = `redirect=${request.nextUrl.pathname}${url.search}`;
  return NextResponse.redirect(url);
}
```

This is the crucial part:
```typescript
  if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
    return NextResponse.next();
  }
  ```
  
  Whenever unhandled error happens in `handleError` we should redirect to `/login`, unless user is already in the `/login` page. Otherwise we'll get `too many redirects` error.
  
If you still face `too many redirects` having this check, maybe the reason is https://github.com/awinogrodzki/next-firebase-auth-edge/issues/84#issuecomment-1674674632

**Comment by awinogrodzki** [comment] 2023-08-30 09:26
@timotiusnc could you share your `middleware.ts` and `next.config.js`?

**Comment by timotiusnc** [comment] 2023-08-30 11:36
Oops, my bad.

You're correct. The problem is in my code. I accidentally removed the crucial part you mentioned.

The reason I accidentally removed it is because I need this feature:
1. There are `UNAUTHED_ONLY_PATHS`. These are paths that only unauthenticated user can access. This is `/register`, `/login`, `/reset-password` (this is `PUBLIC_PATHS` in your example).
2. There are `FULLY_PUBLIC_PATHS`. These are paths that both authenticated and unauthenticated users can access. This is because my website has some paths that belong to this category. I modified the `middleware.js` by early-returning the response (bypassing `next-firebase-auth-edge`).

```
import { authentication } from "next-firebase-auth-edge/lib/next/middleware";

const UNAUTHED_ONLY_PATHS = ["/register", "/login", "/reset-password"];

const FULLY_PUBLIC_PATHS = ["/abc", "/def"];

function redirectToLogin(request: NextRequest) {
  if (UNAUTHED_ONLY_PATHS.includes(request.nextUrl.pathname)) { // I accidentally deleted this checking
    return NextResponse.next();
  }

  ...
}

export async function middleware(request: NextRequest) {
  if (FULLY_PUBLIC_PATHS.includes(pathName)) return NextResponse.next();

  return authentication(request, { ... });
}
```

Thank you, again @awinogrodzki !

**Comment by awinogrodzki** [comment] 2023-08-30 21:18
Closing the issue as resolved. I'll be here If you have any other questions or comments

**Closed by awinogrodzki** 2023-08-30 21:18 UTC
Labels: bug, confirmed, fixed
