### ISSUE TITLE
404 Error on API Routes When Using SRC Folder Structure

### ISSUE THREAD

**Issue by JumboDaniel** [awinogrodzki/next-firebase-auth-edge#241] opened 2024-08-23 13:31 UTC
## Description
When using the `next-firebase-auth-edge` package with a Next.js 14 project that uses the App Router and a `src` folder structure, the automatically generated API routes (`/api/login` and `/api/logout`) return 404 errors.

## Steps to Reproduce
1. Set up a Next.js 14 project with App Router and `src` folder structure
2. Install and configure `next-firebase-auth-edge` as per documentation
3. Implement the middleware as shown bellow
4. Attempt to access `/api/login` or `/api/logout`

## Expected Behavior
The `/api/login` and `/api/logout` routes should be accessible and function as described in the documentation.

## Actual Behavior
Accessing these routes results in a 404 error. Manually creating these routes in `src/app/api/` works, but defeats the purpose of automatic route generation.

## Environment
- Next.js version: 14.2.5
- next-firebase-auth-edge version: 1.6.1
- Node.js version: v20.9.0
- Using App Router: Yes
- Using `src` folder: Yes

## Additional Context
The example provided in the documentation works correctly with a flat project structure. The issue seems to only occur when using a `src` folder structure. I changed the older structure to a flat one and it worked.

## Question
Is there a way to configure the package to work with a `src` folder structure without manually creating the API routes?

##Middleware file
`
import { NextRequest } from "next/server";
import { authMiddleware } from "next-firebase-auth-edge";
import { clientConfig, serverConfig } from "@/lib/firebase/edgeConfig";

export async function middleware(request: NextRequest) {
  return authMiddleware(request, {
    loginPath: "/api/login",
    logoutPath: "/api/logout",
    apiKey: clientConfig.apiKey,
    cookieName: serverConfig.cookieName,
    cookieSignatureKeys: serverConfig.cookieSignatureKeys,
    cookieSerializeOptions: serverConfig.cookieSerializeOptions,
    serviceAccount: serverConfig.serviceAccount,
  });
}
export const config = {
  matcher: [
    "/",
    "/((?!_next|api|.*\\.).*)",
    "/api/login",
    "/api/logout",
  ],
};
`
##Login File
`
"use client";
import * as React from "react";
import Link from "next/link";

////
import { Input } from "@/components/ui/input";
import { RobotoFont } from "@/components/font";
import { SubmitButton } from "@/components/ui/submit-button";
import { PasswordInput } from "@/components/ui/password-input";
import { signInWithPassword } from "@/actions/auth";
import { useFormState } from "react-dom";
import { GoogleSignin } from "@/components/auth/google-signin";

export default function Login() {
  const [state, formAction] = useFormState(signInWithPassword, undefined);
  React.useEffect(() => {
    console.log(state);
    async function SetBrowserCookies() {
      await fetch("/api/login", {
        headers: {
          Authorization: `Bearer ${state?.idToken}`,
        },
      });
    }
    if (state?.success) {
      console.log("is it trying", state?.success, true);
      SetBrowserCookies();
      console.log("is it done", state?.success, true);
    }
  }, [state]);

  return (
    <section className={`space-y-12 max-w-xl my-auto container`}>
      <div className="w-full">
        <h2 className="text-[64px] font-semibold mb-10">Login</h2>
        {/* form */}
        <form action={formAction} className={`${RobotoFont.className}`}>
          <div className="relative mt-4">
            <Input className="" type="email" name="email" required />
            <span className="absolute p-2 pointer-events-none left-4 top-0 transition duration-150 opacity-50 bg-white capitalize ">
              email address
            </span>
          </div>
          <PasswordInput />
          <div className={`${RobotoFont.className} mt-4 text-right`}>
            <Link className="text-[]" href={`/auth/forgot-pasword`}>
              Forgot Password
            </Link>
          </div>
          <div className="text-red-500 not-sr-only text-sm my-2">
            {state?.message}
          </div>
          <SubmitButton
            className="rounded-full w-full uppercase mt-8 relative"
            size={`lg`}
          >
            Login
          </SubmitButton>
        </form>
        <div className={`${RobotoFont.className} text-right mt-4`}>
          <p className="">
            <span className="">Don&apos;t have an account? </span>&nbsp;
            <Link className="text-[]" href={`/auth/signup`}>
              Signup
            </Link>
          </p>
        </div>
        <div className={`${RobotoFont.className} mt-4 text-right`}>
          <div className="my-10">
            <div className="flex items-center gap-4">
              <div className="h-[1px] flex-1 bg-black" />
              <p className="text-black-foreground">or</p>
              <div className="h-[1px] flex-1 bg-black" />
            </div>
          </div>
          <GoogleSignin />
        </div>
      </div>
    </section>
  );
}
`
##form action
`
export async function signInWithPassword(state: FormState, formData: FormData) {
  const email = formData.get("email") as string;
  const password = formData.get("password") as string;
  try {
    const credential = await signInWithEmailAndPassword(FirebaseAuth, email, password);
    const idToken = await credential.user.getIdToken();
    return{
      credential,
      idToken,
      message:"Login successful, redirecting...",
      success:true
    }

  } catch (error: unknown) {
    // console.log("", JSON.stringify(error));
    return mapFirebaseErrorToFormState(error);
  }
}
`

**Comment by awinogrodzki** [comment] 2024-08-26 15:34
Hey @JumboDaniel!

Thanks for reporting. As far as I know, the directory structure should not affect how auth middleware is working. I will try to reproduce the issue and get back to you.

**Comment by awinogrodzki** [comment] 2024-08-26 15:55
Hey @JumboDaniel!

I have modified starter example to use `src` dir: https://github.com/awinogrodzki/next-firebase-auth-edge/pull/245

Everything seems to be working as expected.

Have you moved `middleware.ts` to `src/middleware.ts`?

**Comment by awinogrodzki** [comment] 2024-09-07 11:47
I will close the issue now as it seems to be due to incorrect `middleware.ts` file placement. Feel free to re-open if otherwise

**Closed by awinogrodzki** 2024-09-07 11:47 UTC
Labels: bug, unconfirmed

**Comment by JumboDaniel** [comment] 2024-09-10 10:23
Thank you very much, I found out that was the issue.
