### ISSUE TITLE
Question: how to handle ` The Firebase ID token has been revoked.` error on middleware?

### ISSUE THREAD

**Issue by KeisukeNagakawa** [awinogrodzki/next-firebase-auth-edge#50] opened 2023-05-11 03:25 UTC
Hi, thank you first of all for this great repository. 
I have a question. 

When running in example emulator code in your library(on Safari) with anonymous user only, this error showed up on middleware.
```
The Firebase ID token has been revoked.
```
whichi is caused inside `handleError` on midleware.ts.

Maybe it is a bit of out of scope of this code's responsibility but how can I handle this error when I keep using Anonymous login?

I tried this but did not work(keep showing same error):
1. redirect 
```typescript
// middleware.ts
      if ((error as any)?.code === "auth/id-token-revoked") {
        if (!request.nextUrl.pathname.includes("auth")) {
          return NextResponse.redirect(new URL(`auth`, request.url).toString());
        }
        return NextResponse.next();
```

2. on the redirected page, getIdToken with force refresh option

```typescript
// redirected client page
"use client";
import { useAuth } from "@/components/auth/AuthContext";
import { clientConfig } from "@/fireauth-config-client";
import { useFirebaseAuth } from "@/libs/clientside/firebase";
import { getIdToken, getIdTokenResult } from "firebase/auth";
import { useEffect, useState } from "react";

export default function Page() {
  const { tenant } = useAuth();
  const { getFirebaseAuth } = useFirebaseAuth(clientConfig);
  const [newToken, setNewToken] = useState<string>("");

  useEffect(() => {
    if (!tenant) return;
    const f = async () => {
      const auth = await getFirebaseAuth();
      if (!auth) throw new Error("No auth");
      const currentUser = auth.currentUser;
      if (!currentUser) throw new Error("No current user");
      const newToken = await getIdToken(currentUser, true);
      setNewToken(newToken);
    };
    f();
  }, [tenant]);

  return (<div></div>
  );
}

```

Thanks!

**Comment by awinogrodzki** [comment] 2023-05-20 19:27
Hey @KeisukeNagakawa,

Sorry for the delayed response. I was focused on implementing Next.js 13.4 cache improvements

The error you mention is usually caused by a time difference between firebase emulator and app environment.

This issue should be fixed after https://github.com/awinogrodzki/next-firebase-auth-edge/pull/51

You can use fixed version already by installing `next-firebase-auth-edge@^0.7.5`, but you'll probably get some compatibility issues. Refer to [this migration guide](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/63c9bb2e1512d8d7fe06fcbc41f0064674194057/README.md#migration-to-version-07)

**Closed** 2023-05-28 09:26 UTC
