### ISSUE TITLE
How To add user widget in navbar ?

### ISSUE THREAD

**Issue by rgbskills** [awinogrodzki/next-firebase-auth-edge#66] opened 2023-07-26 09:34 UTC
Hello, I have the following code in my navbar:

```
...
const { user } = useAuth();
...
{!user ? (
            <Button href="/login" className="overflow-hidden">
              <Icons.user />
              <span>Login</span>
            </Button>
          ) : (
            <Button href="/account" className="overflow-hidden">
              {user.photoURL ? (
                <>
                  <span className="-ml-6">
                    <Image
                      priority
                      width={48}
                      height={48}
                      src={user.photoURL}
                      alt="username"
                    />
                  </span>
                  <span className="ml-3">{user.displayName}</span>
                </>
              ) : user.displayName}
            </Button>
          )}
```

If I delete the cookies, I'm still logged in, how do I work around this ?

**Comment by rgbskills** [comment] 2023-07-27 17:13
I guess I need to logout the user if cookies go missing or the token is no longer valid. How would I do that ?

**Comment by awinogrodzki** [comment] 2023-07-31 16:14
Hey @rgbskills,

Your navbar component looks right. The problem your having is inconsistency between cookies and web client `firebase` library. Removing cookies is not enough, you also need to sign out using client `firebase` library as in `starter` example:

https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-starter/app/profile/UserProfile/UserProfile.tsx#L27-L35

Official `firebase` client library stores tokens using `IndexedDB` and possibly falls back to `LocalStorage` on older devices.  You can notice that when you open dev tools after logging in:

<img width="385" alt="Screenshot 2023-07-31 at 18 09 58" src="https://github.com/awinogrodzki/next-firebase-auth-edge/assets/12574743/13e7552b-36a6-487c-ae93-d76139d084d1">

What I recommend to do in such cases is using `Clear site data` in dev tools to avoid state inconsistencies:

<img width="756" alt="Screenshot 2023-07-31 at 18 10 10" src="https://github.com/awinogrodzki/next-firebase-auth-edge/assets/12574743/6264d623-1f66-4d49-ba8b-e0048a07c4a1">

Let me know if that helps. Cheers!

**Comment by rgbskills** [comment] 2023-08-03 15:41
hey @awinogrodzki 

I'm using the same code, I must be doing something wrong then, here is the file where I have the logout button.

[https://github.com/rgbskills/undercover/blob/master/src/app/account/Menu.tsx](https://github.com/rgbskills/undercover/blob/master/src/app/account/Menu.tsx)

**Comment by awinogrodzki** [comment] 2023-08-06 15:37
Hey @rgbskills,

I have tested your code and I have no issues with the logout either by clicking on logout button, or deleting site data. Could you describe what exactly does not work as you would expect?

**Comment by awinogrodzki** [comment] 2023-08-25 09:01
I will close the issue now due to lack of reproduction on my site. If you still face the issue, feel free to comment and we'll reopen. Cheers 🍻

**Closed by awinogrodzki** 2023-08-25 09:01 UTC
